name: Build and Push to Google AR
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write # Required for secret-less Google Auth

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud using the Workload Identity we set up
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/978835754198/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-migrator-sa@gke-kueue.iam.gserviceaccount.com'

      # 2. Configure Docker to talk to your Google Registry
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 3. Build the image and push it to Google Artifact Registry
      - name: Build and Push
        run: |
          docker build -t us-central1-docker.pkg.dev/gke-kueue/gdcv-images/my-package-project:latest .
          docker push us-central1-docker.pkg.dev/gke-kueue/gdcv-images/my-package-project:latest
